name: bash arb

on:
  workflow_dispatch:
  pull_request:

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute Bash Command
        id: execute-bash
        run: |
          sha256sum
